### ISSUE TITLE
Sources/Subs-Tema2.php Require edilememesi ?

### ISSUE THREAD

**Issue by CeeMoo** [CeeMoo/smf-tema-system#1]
Garip birşekilde require edilen Sources-Tema2.php bende hata alıyor : require_once(/var/www/html/smf2/Sources/Subs-Tema2.php): failed to open stream: No such file or directory

Smf güvenlik ile ilgili olabilir ama dosya izinlerim 777 buna karışmaması lazım.

Örnek kategori ekleme function tema2.php içine aldığımda sorun oluşturmuyor.

**Comment by snrj** [comment]
sources klasöründe Subs-Tema2.php var mı bi kontrol et
